---
- hosts: all
  become: yes
  roles:
    - common
    - docker
    - kubernetes

- hosts: masters
  become: yes
  roles:
    - master

- hosts: workers
  become: yes
  roles:
    - worker

- hosts: masters
  become: yes
  roles:
    - deploy
